Repository palashmunshi/Gatepass-Portal, pull requests merged in 2023-03, with the labels that each got.

#13 Parameter setting
  client-side/src/Components/adminComponent/Settings/parameter.js
  server-side/node-mssql-crud/src/controllers/admin.controller.js
  server-side/node-mssql-crud/src/routes/admin.routes.js
Labels: enhancement

#22 Auto fetch
  client-side/src/Components/guardComponent/Checkin/checkinDetails/checkinDetails.js
  client-side/src/Components/guardComponent/Checkout/checkoutDetails/checkoutDetails.js
Labels: enhancement

#24 Check in out fix
  client-side/src/Components/guardComponent/Checkin/checkinDetails/checkinDetails.js
  client-side/src/Components/guardComponent/Checkout/checkoutDetails/checkoutDetails.js
  server-side/node-mssql-crud/src/controllers/guard.controller.js
  server-side/node-mssql-crud/src/database/query.js
  server-side/node-mssql-crud/src/routes/guard.routes.js
Labels: enhancement

#26 Alert fix
  client-side/src/Components/studentComponent/Gatepasses/LocalFixed/Form/LFform.js
Labels: enhancement

#29 Search bar for CheckIn and CheckOut #23
  client-side/src/Components/guardComponent/Checkin/checkinDetails/checkinDetails.js
  client-side/src/Components/guardComponent/Checkin/checkinDetails/checkinDetails.scss
  client-side/src/Components/guardComponent/Checkout/checkoutDetails/checkoutDetails.js
  client-side/src/Components/guardComponent/Checkout/checkoutDetails/checkoutDetails.scss
  client-side/src/Shared/Navbar/navbar.scss
  client-side/src/Shared/Sidebar/adminSidebar.js
  client-side/src/Shared/Sidebar/guardSidebar.js
  client-side/src/Shared/Sidebar/sidebar.scss
  client-side/src/Shared/Sidebar/studentSidebar.js
  client-side/src/Shared/Sidebar/wardenSidebar.js
  client-side/src/assets/NU-logo.png
Labels: enhancement

#33 Visitor check in check out page
  client-side/src/App.js
  client-side/src/Components/guardComponent/Checkout/checkoutDetails/checkoutDetails.js
  client-side/src/Components/guardComponent/VisitorCheckin/checkin.js
  client-side/src/Components/guardComponent/VisitorCheckin/checkin.scss
  client-side/src/Components/guardComponent/VisitorCheckin/checkinDetails/checkinDetails.js
  client-side/src/Components/guardComponent/VisitorCheckin/checkinDetails/checkinDetails.scss
  client-side/src/Components/guardComponent/VisitorCheckout/checkout.js
  client-side/src/Components/guardComponent/VisitorCheckout/checkout.scss
  client-side/src/Components/guardComponent/VisitorCheckout/checkoutDetails/checkoutDetails.js
  client-side/src/Components/guardComponent/VisitorCheckout/checkoutDetails/checkoutDetails.scss
  client-side/src/Shared/Sidebar/guardSidebar.js
  client-side/src/Shared/Sidebar/sidebar.scss
Labels: UI design fix

#41 Partially Completed the users page on admin
  client-side/src/Components/adminComponent/Settings/User/User.js
  client-side/src/Components/adminComponent/Settings/User/User.scss
  server-side/node-mssql-crud/src/controllers/admin.controller.js
  server-side/node-mssql-crud/src/database/query.js
  server-side/node-mssql-crud/src/routes/admin.routes.js
Labels: High Priority

#45 Search Bar implemented in users page
  client-side/src/Components/adminComponent/Settings/User/User.js
  client-side/src/Components/adminComponent/Settings/User/User.scss
Labels: enhancement
