Repository palashmunshi/Gatepass-Portal, pull requests merged in 2023-05, with the labels that each got.

#89 Accept student gatepass api
  server-side/node-mssql-crud/src/controllers/warden.controller.js
  server-side/node-mssql-crud/src/database/query.js
  server-side/node-mssql-crud/src/routes/warden.routes.js
Labels: enhancement

#96 DashBoard others API
  server-side/node-mssql-crud/src/controllers/warden.controller.js
  server-side/node-mssql-crud/src/database/query.js
  server-side/node-mssql-crud/src/routes/warden.routes.js
Labels: enhancement

#93 Auto batches
  server-side/node-mssql-crud/src/controllers/warden.controller.js
  server-side/node-mssql-crud/src/database/query.js
  server-side/node-mssql-crud/src/routes/warden.routes.js
Labels: enhancement

#100 Gatepass other Dashboard
  client-side/src/Components/wardenComponent/OtherDashboard.js
  client-side/src/Components/wardenComponent/OtherDashboardGatepasses/Modal.js
  client-side/src/Components/wardenComponent/OtherDashboardGatepasses/OtherGatepass.js
  server-side/node-mssql-crud/src/controllers/warden.controller.js
  server-side/node-mssql-crud/src/database/query.js
Labels: enhancement, High Priority

#104 Warden Approved/Cancelled Student- Profile/LocalFlexible/Outstation
  client-side/src/App.js
  client-side/src/Components/studentComponent/Gatepasses/LocalFixed/LocalFixed.js
  client-side/src/Components/studentComponent/Gatepasses/LocalFlexible/LocalFlexible.js
  client-side/src/Components/studentComponent/Gatepasses/Outstation/Outstation.js
  client-side/src/Components/studentComponent/MyProfile.js
  client-side/src/Components/wardenComponent/Approve_cancel.js
  client-side/src/Shared/NavbarTailwind/StudentNavbar.js
  client-side/src/Shared/SideBarTailWind/StudentSidebar.js
  client-side/src/Shared/SideBarTailWind/WardenSidebar.js
Labels: enhancement

#107 Canceled/approved/rejected gatepasses page made
  client-side/src/App.js
  client-side/src/Components/wardenComponent/Approve_cancel.js
  client-side/src/Components/wardenComponent/ApprovedCancelled/ApproveCancel.js
  client-side/src/Components/wardenComponent/ApprovedCancelled/ModalApproved.js
  client-side/src/Components/wardenComponent/ApprovedCancelled/ModalRejected.js
  client-side/src/Shared/NavbarTailwind/StudentNavbar.js
  server-side/node-mssql-crud/src/controllers/warden.controller.js
  server-side/node-mssql-crud/src/database/query.js
  server-side/node-mssql-crud/src/routes/warden.routes.js
Labels: bug, enhancement

#109 changed file struicture in local flexible with additional code changes
  client-side/src/Components/studentComponent/Gatepasses/LocalFlexible/Form/LFform.js
  client-side/src/Components/studentComponent/Gatepasses/LocalFlexible/LocalFlexible.js
Labels: enhancement

#112 Date api
  server-side/node-mssql-crud/src/controllers/student.controller.js
  server-side/node-mssql-crud/src/routes/student.routes.js
Labels: enhancement

#114 All the dates and time are being fetched by the server
  client-side/src/Components/studentComponent/Gatepasses/LocalFixed/Form/LFform.js
Labels: bug

#115 Apply local flexible
  client-side/src/Components/studentComponent/Gatepasses/LocalFlexible/Form/LFform.js
  client-side/src/Components/studentComponent/Gatepasses/LocalFlexible/LocalFlexible.js
  server-side/node-mssql-crud/src/controllers/student.controller.js
  server-side/node-mssql-crud/src/database/query.js
  server-side/node-mssql-crud/src/routes/student.routes.js
Labels: enhancement, High Priority

#118 Sidebar changed to default
  client-side/src/Components/guardComponent/Checkin/checkin.js
Labels: enhancement

#119 Time of apply in local flexible
  client-side/src/Components/studentComponent/Gatepasses/LocalFlexible/Form/LFform.js
Labels: bug

#124 Get student gatepasses api
  server-side/node-mssql-crud/src/controllers/student.controller.js
  server-side/node-mssql-crud/src/database/query.js
  server-side/node-mssql-crud/src/routes/student.routes.js
Labels: enhancement

#126 query changed
  server-side/node-mssql-crud/src/database/query.js
Labels: bug

#129 Student my profile
  client-side/src/Components/studentComponent/MyProfile.js
  client-side/src/Shared/NavbarTailwind/StudentNavbar.js
  client-side/src/Shared/SideBarTailWind/StudentSidebar.js
Labels: enhancement
